---
###############################################################################
# Main Site Playbook - Web Server Stack Provisioning
# Description: Orchestrates the deployment of Apache, PHP 8.2, and Composer
# Target OS: Red Hat Enterprise Linux 9 or compatible distribution
# Author: DevOps Team
# Version: 1.0.0
###############################################################################

- name: Deploy Web Server Stack with VirtualHosts on RedHat 9
  # hosts: webservers
  hosts: local
  connection: local
  become: true
  gather_facts: true
  
  # Variables for VirtualHosts configuration
  vars:
    # VirtualHosts list
    vhosts_list:
      # Production site with PHP 8.2
      # - domain: "example.com"
      #   username: "example"
      #   php_version: "8.2"
      #   state: "present"
      #   server_admin: "admin@example.com"
      #   server_alias: "www.example.com"
      
      # Development site with PHP 8.1
      - domain: "dev.rfan.my.id"
        username: "devuser"
        php_version: "8.1"
        state: "present"
        server_admin: "dev@rfan.my.id"
        log_level: "debug"
      
      # Legacy site with PHP 7.4
      # - domain: "legacy.example.com"
      #   username: "legacy"
      #   php_version: "7.4"
      #   state: "present"
      #   server_admin: "legacy@example.com"
      
      # Staging site with PHP 8.3
      # - domain: "staging.example.com"
      #   username: "staging"
      #   php_version: "8.3"
      #   state: "present"
      #   server_admin: "staging@example.com"
      
      # Removed/disabled site (will be deleted)
      # - domain: "old.example.com"
      #   username: "olduser"
      #   php_version: "7.4"
      #   state: "absent"
      #   archive_on_remove: true
    
    # Global VirtualHost settings
    vhosts_userdir_enabled: true
    vhosts_ssl_enabled: false
    vhosts_create_dirs: true
  
  # Pre-tasks run before roles
  pre_tasks:
    - name: Display target host information
      ansible.builtin.debug:
        msg: "Deploying to {{ inventory_hostname }} ({{ ansible_distribution }} {{ ansible_distribution_version }})"
    
    - name: Verify Red Hat Enterprise Linux 9 or compatible distribution
      ansible.builtin.assert:
        that:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "9"
        fail_msg: "This playbook requires Red Hat Enterprise Linux 9 or compatible distribution. Detected: {{ ansible_distribution }} {{ ansible_distribution_version }}"
        success_msg: "Operating system verified: Red Hat Enterprise Linux 9 or compatible distribution"
    
    - name: Update system packages cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
    
    - name: Ensure required users exist for VirtualHosts
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: "{{ 'present' if item.state == 'present' else 'absent' }}"
        shell: /bin/bash
        create_home: true
      loop: "{{ vhosts_list }}"
      tags: ['users', 'vhosts']
  
  # Roles execution order
  roles:
    - role: common
      tags: ['common', 'base']
      
    - role: httpd
      tags: ['httpd', 'apache', 'webserver']
      
    - role: php
      tags: ['php', 'composer']
      
    - role: vhosts
      tags: ['vhosts']
  
  # Post-tasks run after all roles
  post_tasks:
    - name: Verify Apache is running
      ansible.builtin.service:
        name: httpd
        state: started
      check_mode: true
      register: httpd_status
      changed_when: false
    
    - name: Verify PHP installation
      ansible.builtin.command: php -v
      register: php_version
      changed_when: false
      failed_when: php_version.rc != 0
    
    - name: Display PHP version
      ansible.builtin.debug:
        msg: "{{ php_version.stdout_lines[0] }}"
    
    - name: Verify Composer installation
      ansible.builtin.command: "{{ composer_install_path }} --version"
      register: composer_version
      changed_when: false
      failed_when: composer_version.rc != 0
    
    - name: Display Composer version
      ansible.builtin.debug:
        msg: "{{ composer_version.stdout_lines[0] }}"
    
    - name: Deployment summary
      ansible.builtin.debug:
        msg: 
          - "========================================"
          - "Web Server Stack Deployment Complete"
          - "========================================"
          - "Host: {{ inventory_hostname }}"
          - "Apache: Installed and Running"
          - "PHP: {{ php_version.stdout_lines[0] }}"
          - "Composer: {{ composer_version.stdout_lines[0] }}"
          - "========================================"
    
    - name: Display VirtualHosts deployment summary
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "VirtualHosts Deployment Complete"
          - "========================================="
          - "Active domains:"
          - "{{ vhosts_list | selectattr('state', 'equalto', 'present') | map(attribute='domain') | list }}"
          - "========================================="
          - "Test your VirtualHosts:"
          - "  curl http://example.com"
          - "  curl http://dev.example.com/info.php"
          - "========================================="
